---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: observe-logs
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - CAP_FOWNER
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:observe:observe-logs
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: observe-events
allowPrivilegedContainer: false
allowHostNetwork: false
allowHostDirVolumePlugin: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAs
  uid: 65534
seLinuxContext:
  type: MustRunAs
users:
  - system:serviceaccount:observe:observe-events
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: observe-metrics
allowPrivilegedContainer: false
allowHostNetwork: false
allowHostDirVolumePlugin: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAs
  uid: 65534
seLinuxContext:
  type: MustRunAs
users:
  - system:serviceaccount:observe:observe-metrics
