apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
spec:
  template:
    spec:
      containers:
        - name: kube-state-events
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 1Gi
